### ISSUE TITLE
Density Tables - Clarification

### ISSUE THREAD

**Issue by pymilo** [ehsteve/roentgen#13]
The documentation says that densities and other physical parameters were grabbed from http://www.nist.gov/pml/data/xraycoef/index.cfm

However, for example for Argon (Z=18), the nominal density in J. H. Hubbell+ and S. M. Seltzer is 1.662E-03 g/cm3, while in the table roentgen/roentgen/data/elements_densities.csv is 0.86 g/cm3.

Although the user can input any desired density for a specific material, It will be also helpful to indicate what are the standard conditions for the "nominal densities" (i.e. room temperature and 1 atm).

**Comment by ehsteve** [comment]
Densities have been replaced with those provided by NIST [here](https://physics.nist.gov/PhysRefData/XrayMassCoef/tab1.html). Unfortunately, it does not state what the conditions were. I assume at STP.
