### ISSUE TITLE
Plans to support chemical compounds not in the database through the NIST web api?

### ISSUE THREAD

**Issue by samaloney** [ehsteve/roentgen#22]
Just thinking it would be great to be able to support compounds/materials not in the database using the chemical formula option of the web interface/api at https://physics.nist.gov/PhysRefData/FFast/html/form.html ?

**Comment by samaloney** [comment]
So I created a fairly nasty hack to support this it using the same approach as the precomputed NIST values and given in Equation 6 of [NIST Chap 2](https://physics.nist.gov/PhysRefData/XrayMassCoef/chap2.html)

```python
from functools import partial

def create_material(name=None, fractional_masses=None, thickness=None, density=None):
    material = Material('H', thickness, density)
    material.name = name
    # Probably don't need this
    material.density = density

    
    def func(fractional_masses, e):
        return sum([MassAttenuationCoefficient(element).func(e) * frac_mass 
                             for element, frac_mass in fractional_masses.items()])
    
    material_func = partial(func, fractional_masses)

    material.mass_attenuation_coefficient.func = material_func
    return material
```

Now given the fractional elemental mass of a material you can calculate the transmission etc so for kapton which is not in the NIST tables

```
>>>kapton = create_material(name='kapton', 
>>>                         fractional_masses={'H': 0.026362, 'C': 0.691133, 'N': 0.073270, 'O': 0.209235},
>>>                         thickness=1*u.mm, density=1.42*u.g/u.cm**3 )
>>>kapton
Material(kapton) 1.0 mm 1420.0 kg / m3)
>>>kapton.transmission([4, 8, 16, 32, 64]*u.keV)
array([8.09891602e-04, 4.16954275e-01, 8.80128352e-01, 9.62125963e-01,
       9.74883257e-01])
```

**Comment by ehsteve** [comment]
@samaloney I created the `Compound` object to enable adding materials together (https://roentgen.readthedocs.io/en/latest/api/roentgen.absorption.Compound.html). I think this does most of what you are trying to do here. You can't do fractional masses as you did here. I like the idea of moving this capability up to the `MassAttenuationCoefficient` class and I also like the idea of adding a database of common materials.

**Comment by ehsteve** [comment]
@samaloney I wrote up a potential refactor to enable this functionality. Would appreciate your feedback on #26. Thanks!
