### ISSUE TITLE
Interpolated Mass attenuation values don't seem to match the reference table data

### ISSUE THREAD

**Issue by samaloney** [ehsteve/roentgen#24]
Comparing the graphs from the NIST source page [here](https://physics.nist.gov/PhysRefData/XrayMassCoef/ElemTab/z52.html) the edges don't seem to be being interpolated properly.

![Te_mass_atten](https://user-images.githubusercontent.com/24570854/91473525-eb5e9380-e890-11ea-94fb-9c8ed086860a.png)

Code to create plot
```python
e = np.linspace(1e-3, 20, 10000)*u.MeV
te = MassAttenuationCoefficient('Te')
plt.plot(e, te.func(e))
plt.loglog()
plt.xlim(1e-3, 1e2)
plt.ylim(1e-2, 1e4)
plt.xlabel('Photon Energy (MeV)')
plt.ylabel(r'$\mu / \rho$ (cm$^{2}$ g$^{-1}$)')
plt.title('Te')
```

**Comment by samaloney** [comment]
It seems scipy's interp1d doesn't handle multivalued/non-monotonic x-values, attached  plot shows the effect, evaluating the attenuation coefficient at same values used for the interpolation.

![interp_issue](https://user-images.githubusercontent.com/24570854/91504705-cc2e2900-e8c5-11ea-9bd5-d58410fcac47.png)

**Comment by rschwartz70** [comment]
where is the interp1d done in your codelet. If I could see the issue in detail I could determine whether my IDL code would suffer the same issue.

**Comment by samaloney** [comment]
It's these lines, where `self.energy.value` and `self.data.value` are values from the NIST tables and the interpolation function is setup as `self._f` and then calling `self._f(<log of engery>)` returns the an interpolated value.

https://github.com/ehsteve/roentgen/blob/44467581886eaa355cb991b3778bb8de7e30a47d/roentgen/absorption/material.py#L312-L320

I altered the first of any repeating data points bit an tiny fraction (1e-10) and this resolved the issue but not sure if that is a good solution or not.

![interp_fixed](https://user-images.githubusercontent.com/24570854/91538314-931aa680-e90f-11ea-81a5-72cbe0e4eb9c.png)

**Comment by rschwartz70** [comment]
interp1d should be called using assume_sorted as true because the data are already sorted

**Comment by rschwartz70** [comment]
More extensive NIST tables exist into the pair production energy range. There are several independent processes that go into the mass atten coefficients that should be independently specifiable.  It would require a trivial elaboration of this code.  I am going to enlist Laura and Danny on this effort.

**Comment by ehsteve** [comment]
Hey @rschwartz70 and @samaloney! sorry it took me so long to reply, I was on vacation last week. Thanks for noticing and reporting this bug. I had thought I had looked at this but apparently not closely enough (see https://roentgen.readthedocs.io/en/latest/examples/tutorial1.html)! It looks like @rschwartz70 solution works for me. I'll admit that I don't understand why it works because the documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html) states that it will sort the data itself by default so this should not be needed.

![Figure_1](https://user-images.githubusercontent.com/739053/91725836-459b7500-eb6d-11ea-9b76-c303e209bdf6.png)

**Comment by ehsteve** [comment]
@rschwartz70 I'd be happy to expand the data set here if you can point me to the right place. Can I ask what you guys are working on? I'm happy to see that some is beginning to use this!

**Comment by rschwartz70** [comment]
This is for STIX but I'm going to use these NIST data for Be to fix
the GOES16 response problem.  But it also demonstrated that using XCOM data
from NIST is a little better than the Berger and Seltzer tables/fits that
I've been using in XSEC (ssw/packages/xray) for 40 years (pre IDL).  The
XCOM tables from NIST used date back to before 1995.  Those tables can be
found in a FITS file in SSW
$SSW/packages/xray/dbase/xcom.fits

read_mat_xcom.pro in xray is an idl interface into individual tables.

An updated XCOM version, with ASCII tables, is found here
https://physics.nist.gov/PhysRefData/Xcom/Text/download.html

The DOS file is an archive that can be unpacked by 7zip.  Probably the MAC
version works for the rest of you. I may use the DOS files to update my
tables.

A word about xsec.  Those were log/log stepwise fits around edges. Put out
by NIST people.  Probably the biggest issue is that in the XCOM version
there is much more edge detail and there are no log/log coefficients, only
the data and the double energy double cross-section solution at the k/l
edges which caused the scipy and not the numpy interpol1d glitch

I'd be so happy if we had a unified database between ssw and StevePy for
xsections.
Thanks

**Comment by ehsteve** [comment]
@samaloney would you be willing to review my proposed fix in PR #25?

**Comment by samaloney** [comment]
Just a final note on this the `assume_sorted` keyword only works for floats which is fine in this case as astropys`Quantity` are always cast to floats.

**Comment by rschwartz70** [comment]
The xcom FITS file I've been using has a typo in the spelling of Fluorine.
It has used Flourine. That's not US or British English. I'm going to
correct that entry and load the file back into
ssw/packages/xray/dbase/xcom.fits
Richard

**Comment by ehsteve** [comment]
This was fixed.
