### ISSUE TITLE
Potential renaming and refactor

### ISSUE THREAD

**Issue by ehsteve** [ehsteve/roentgen#26]
Creating a `Substance` class which will allow users to define either an element or a compound.
```python
si1 = Substance('si')
si2 = Substance('si', density=1*u.kg/u.m^3)
kapton = Substance({'H': 0.026362, 'C': 0.691133, 'N': 0.073270, 'O': 0.209235}, name='kapton')
```
Density is not required to be provided for creation. A substance created with a dictionary does require a name to be provided. This would enable the following
```python
MassAttenuationCoefficient(si1)
MassAttenuationCoefficient(si2)
MassAttenuationCoefficient(kapton)
Material(si2, thickness=100*u.micron)
Material(kapton, thickness=100*u.micron)
```
The following would error since no density has been defined for `si1`, `Material(si1, thickness=100*u.micron)`

The following constructions would still be possible
```python
MassAttenuationCoefficient('si')
Material('he', density=1*u.kg/u.m^3)
```
A `Substance` object would be created automatically under the hood. The `Substance` class is in charge of interpreting these inputs and would be removed from `MassAttenuationCoefficient` and `Material`.

The `Compound` class would be renamed `MaterialStack` to remove possible confusion. The same functionality would remain.

**Comment by samaloney** [comment]
Yea I was thinking along the same lines need to differentiate between a material/substance and a series of layers. Introduction of a `Substance` class seems like a nice way to add the extra functionality without losing the ease of  `Material('cdte', thickness=100*u.micron)`.

Would you envisage handling creation of a Material with a dictionary (`Material({'H': 0.026362, 'C': 0.691133, 'N': 0.073270, 'O': 0.209235}, thickness=100*u.micron)`), or make this explicit through the creation of a Substance?

**Comment by ehsteve** [comment]
I'm glad you agree. Not sure about allowing a dictionary as input to Material because I feel like you need to give the Substance a string for a name. Creating a string out of only that dictionary to identify what Substance you created won't work and asking the user to memorize some strange dictionary pattern that involves a name key is not elegant. That could be more easily documented in a class constructor. What do you think?

**Comment by ehsteve** [comment]
Adding this functionality to 'Material' so no new object was needed.
