### ISSUE TITLE
Mass attenuation coefficients are erroneously interpolated below 1 keV

### ISSUE THREAD

**Issue by wtbarnes** [ehsteve/roentgen#38]
The data included in `roentgen` from NIST only extend down to 1 keV (~12 Angstrom). However, when the mass attenuation coefficients are interpolated to the input energy, any values outside of the bounds are filled with zeros,

https://github.com/ehsteve/roentgen/blob/160e944ea8d402716c19209488e698ce932f3892/roentgen/absorption/material.py#L315-L324

This can be seen for the following energy range which extends from ~0.2 to ~12 keV for Al,

```python
import astropy.units as u
import astropy.constants as const
import matplotlib.pyplot as plt
import numpy as np
from roentgen.absorption import Material

al = Material('Al',100*u.nm)

wavelength = np.arange(1,60,1) * u .angstrom
energy = const.h * const.c / wavelength

transmission = al.transmission(energy)
mac = al.mass_attenuation_coefficient.func(energy)
```

Plotting the mass attenuation coefficient over the whole energy range, it can be seen that the mass attenuation coefficient goes to 1 once we interpolate outside of the data range (below 1 keV).

![image](https://user-images.githubusercontent.com/8676141/181618290-3f59ee3b-8284-4513-b182-f9abf83a2ac1.png)

This also has the effect of forcing the transmission coefficient 1 at low energies (long wavelengths),

![image](https://user-images.githubusercontent.com/8676141/181618582-ea480c93-acc0-4582-9adb-d5ab149ab22e.png)

For comparison, here is the plot from CXRO,

![image](https://user-images.githubusercontent.com/8676141/181619418-fb6e02fb-438f-451b-ba56-4ad5526a2e35.png)

Clearly, below 1 keV (~12 angstrom), the transmission is not constant and not 1.

If supporting energies below 1 keV is out of scope for `roentgen`, then that's fine, but I think the interpolation should either a) error when energies outside of the data bounds are input or b) fill with NaN outside of the bounds. As it currently stands, the code computes clearly incorrect transmission/absorption outside of the data bounds. Additionally, this should be stated clearly in the documentation.

**Comment by ehsteve** [comment]
So sorry I missed this @wtbarnes. Not sure how given how much I've been working on this package recently. I'll fix this and make a new release. Thanks for pointing this out!

**Comment by ehsteve** [comment]
Could you review the pull request to address this issue please @wtbarnes?

For the future I'd like to extend the range down to below 1 keV by merging in CXRO data but that would be for a future release.
