### ISSUE TITLE
Downgrade min python version to 3.7/3.8

### ISSUE THREAD

**Issue by samaloney** [ehsteve/roentgen#47]
Python 3.7 EOL is 2023-06-27 and 3.8 EOL is 2024-10 so unless there a dependancy or python feature issue why not support these?

**Comment by Cadair** [comment]
https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by samaloney** [comment]
So 3.7 is a bit too old and in April 3.8 will also be too old?

**Comment by Cadair** [comment]
yes

**Comment by ehsteve** [comment]
Looks like @Cadair answered this so closing.
